apiVersion: v1
kind: Service
metadata:
  name: jinvani-ott-backend-service
  namespace: default
spec:
  selector:
    app: jinvani-ott-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
